apiVersion: 1

templates:
  - name: workout_service_slack_template
    template: |
      {{ define "workout_service.slack.title" }}
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:fire:{{ end }}] {{ .CommonLabels.alertname }}
      {{ end }}

      {{ define "workout_service.slack.message" }}
      *Severidade:* {{ .CommonLabels.severity | toUpper }}
      *Serviço:* {{ .CommonLabels.service }}
      *Detalhes:* {{ .CommonAnnotations.description }}

      {{ if gt (len .Alerts.Firing) 0 }}
      *Alertas Ativos:*
      {{ range .Alerts.Firing }}
      • {{ .Labels.resource_type }}{{ if .Labels.operation }} - {{ .Labels.operation }}{{ end }}: {{ .Value | printf "%.2f" }}
      {{ end }}
      {{ end }}

      {{ if gt (len .Alerts.Resolved) 0 }}
      *Alertas Resolvidos:*
      {{ range .Alerts.Resolved }}
      • {{ .Labels.resource_type }}{{ if .Labels.operation }} - {{ .Labels.operation }}{{ end }}
      {{ end }}
      {{ end }}

      *Início:* {{ .CommonAnnotations.startsAt | date "02/01/2006 15:04:05" }}
      *Dashboard:* {{ .CommonAnnotations.dashboardURL }}
      {{ end }}

  - name: workout_service_email_template
    template: |
      {{ define "workout_service.email.subject" }}
      [{{ .Status | toUpper }}] Alerta: {{ .CommonLabels.alertname }} - {{ .CommonLabels.service }}
      {{ end }}

      {{ define "workout_service.email.message" }}
      <h2>{{ .CommonLabels.alertname }}</h2>
      
      <p><strong>Status:</strong> {{ .Status | toUpper }}</p>
      <p><strong>Severidade:</strong> {{ .CommonLabels.severity | toUpper }}</p>
      <p><strong>Serviço:</strong> {{ .CommonLabels.service }}</p>
      <p><strong>Detalhes:</strong> {{ .CommonAnnotations.description }}</p>

      {{ if gt (len .Alerts.Firing) 0 }}
      <h3>Alertas Ativos:</h3>
      <ul>
      {{ range .Alerts.Firing }}
        <li>{{ .Labels.resource_type }}{{ if .Labels.operation }} - {{ .Labels.operation }}{{ end }}: {{ .Value | printf "%.2f" }}</li>
      {{ end }}
      </ul>
      {{ end }}

      {{ if gt (len .Alerts.Resolved) 0 }}
      <h3>Alertas Resolvidos:</h3>
      <ul>
      {{ range .Alerts.Resolved }}
        <li>{{ .Labels.resource_type }}{{ if .Labels.operation }} - {{ .Labels.operation }}{{ end }}</li>
      {{ end }}
      </ul>
      {{ end }}

      <p><strong>Início:</strong> {{ .CommonAnnotations.startsAt | date "02/01/2006 15:04:05" }}</p>
      <p><a href="{{ .CommonAnnotations.dashboardURL }}">Acessar Dashboard</a></p>
      {{ end }} 