export enum NotificationType {
  TRAINING_REMINDER = 'TRAINING_REMINDER',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  GOAL_ACHIEVED = 'GOAL_ACHIEVED',
  CLASS_CANCELED = 'CLASS_CANCELED',
  CLASS_RESCHEDULED = 'CLASS_RESCHEDULED',
  NEW_ASSESSMENT = 'NEW_ASSESSMENT',
  MAINTENANCE_ALERT = 'MAINTENANCE_ALERT',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
  WORKOUT_REMINDER = 'WORKOUT_REMINDER',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  CLASS_REMINDER = 'CLASS_REMINDER',
  MEMBERSHIP_EXPIRING = 'MEMBERSHIP_EXPIRING',
  ASSESSMENT_REMINDER = 'ASSESSMENT_REMINDER',
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PROMOTION = 'PROMOTION',
  FEEDBACK_REQUEST = 'FEEDBACK_REQUEST',
  CUSTOM = 'CUSTOM'
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  PARTIALLY_SENT = 'PARTIALLY_SENT',
  GROUPED = 'GROUPED',
  CANCELED = 'CANCELED'
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  WHATSAPP = 'WHATSAPP'
} 