global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'  # Substitua pela URL real do webhook do Slack

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#fitness360-alerts'
        send_resolved: true
        title: ':bangbang: {{ .Status | toUpper }} - {{ .CommonLabels.alertname }}'
        title_link: 'http://localhost:9093/#/alerts?receiver={{ .Receiver }}'
        text: >-
          {{ range .Alerts }}
            *Alerta:* {{ .Annotations.summary }}
            *Descrição:* {{ .Annotations.description }}
            *Severidade:* {{ .Labels.severity }}
            *Serviço:* {{ .Labels.service }}
            *Início:* {{ .StartsAt.Format "2006-01-02T15:04:05Z07:00" }}
          {{ end }}

  - name: 'slack-critical'
    slack_configs:
      - channel: '#fitness360-critical'
        send_resolved: true
        title: ':rotating_light: CRÍTICO - {{ .CommonLabels.alertname }}'
        title_link: 'http://localhost:9093/#/alerts?receiver={{ .Receiver }}'
        text: >-
          {{ range .Alerts }}
            *Alerta:* {{ .Annotations.summary }}
            *Descrição:* {{ .Annotations.description }}
            *Serviço:* {{ .Labels.service }}
            *Início:* {{ .StartsAt.Format "2006-01-02T15:04:05Z07:00" }}
          {{ end }}

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#fitness360-warnings'
        send_resolved: true
        title: ':warning: AVISO - {{ .CommonLabels.alertname }}'
        title_link: 'http://localhost:9093/#/alerts?receiver={{ .Receiver }}'
        text: >-
          {{ range .Alerts }}
            *Alerta:* {{ .Annotations.summary }}
            *Descrição:* {{ .Annotations.description }}
            *Serviço:* {{ .Labels.service }}
            *Início:* {{ .StartsAt.Format "2006-01-02T15:04:05Z07:00" }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 