global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'workout-service'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s
    scrape_timeout: 3s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'workout-service' 