apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fitness360

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: auth-service
  app.kubernetes.io/part-of: fitness360
  app.kubernetes.io/managed-by: kustomize 