global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-svc:3001']

  - job_name: 'feedback-service'
    static_configs:
      - targets: ['feedback-svc:3005']

  - job_name: 'members-service'
    static_configs:
      - targets: ['members-svc:3003']

  - job_name: 'billing-service'
    static_configs:
      - targets: ['billing-svc:3004'] 