global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuração de alerta
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Regras de alerta
rule_files:
  - 'rules/*.yml'

# Configurações de scraping
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-api:3001']
        labels:
          service: 'auth'

  - job_name: 'members-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['members-api:3003']
        labels:
          service: 'members'

  - job_name: 'billing-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['billing-api:3004']
        labels:
          service: 'billing'

  - job_name: 'feedback-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['feedback-api:3005']
        labels:
          service: 'feedback'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
        labels:
          service: 'kafka' 